version: '3.8'
services:
  url-shortner:
    container_name: "url-shortner"
    image: "url-shortner"
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:prod"]
    env_file:
      - .env.production
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
    restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
networks:
  nesjs-network:
    driver: bridge