version: '3.8'
services:
  url-shortner:
    container_name: "url_shortner${node_env}"
    image: "url_shortner${node_env}"
    environment:
      - node_env:${node_env}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:${node_env}"]
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
    restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
networks:
  nesjs-network:
    driver: bridge